@startuml ArduinoNative
top to bottom direction
' --- left to right direction

package "ArduinoNative Interfaces" as Interfaces {

    interface "IPrint" as iPrint {
        + {abstract} print(str : const char[])  : void

        + {abstract} print(value : uint8_t)     : void
        + {abstract} print(value : uint16_t)    : void
        + {abstract} print(value : uint32_t)    : void

        + {abstract} print(value : int8_t)      : void
        + {abstract} print(value : int16_t)     : void
        + {abstract} print(value : int32_t)     : void
' --- KD3!!! todo println

        + {abstract} write(buffer : const uint8_t * , length: size_t ) : size_t
    }

    interface "IStream" as iStream {
        + {abstract} available(void) : int
        + {abstract} readBytes(buffer : uint8_t *, length : size_t ) : size_t
    }

    '* Stream.h : class Stream : public Print  *'
    iStream <|--- iPrint : <<use>>
    '*  TODO  <<derive>>  *'
}

package "ArduinoNative Library" as DeviceClasses {

    class "Serial_" as Serial_ {
        * Serial_(stream Stream& )

        + setStream(stream : Stream& )    : void
        + begin(baudrate : unsigned long) : void
        + end()                           : void

        + print(str : const char[])    : void

        + print  (value : uint@_t)     : void
        + println(value : uint@_t)     : void

        + write(buffer : const uint8_t * , length: size_t ) : size_t

        + available(void) : int
        + readBytes(buffer : uint8_t *, length : size_t ) : size_t
    }

    '*    ??? iStream  <|... Serial_ : <<realize>> *'
    iStream  <|--- Serial_ : <<use>>
    iPrint   <|... Serial_ : <<realize>>


    class "Terminal" as Terminal {
        '* default CTor *'
        + print(str : const char[]) : void

        + print  (value : uint@_t)  : void
        + println(value : uint@_t)  : void

        + write(buffer : const uint8_t * , length: size_t ) : size_t

        + available(void) : int
        + readBytes(buffer : uint8_t *, length : size_t ) : size_t
    }

    iStream <|... Terminal : <<realize>>
    iPrint  <|... Terminal : <<realize>>

' --- KD3!!! todo other methods
}

package "ArduinoNative Application" as Library {
    class "Arduino" as arduNameSpaceProxy  {

        + setup(
            getSystemTickFunc : (unsigned long (*)()   ),
            systemDelayFunc   : (void (*)(unsigned long)) ) : void

        + loop () : void
    }



    arduNameSpaceProxy -up-|> Terminal : <<use>>

    arduNameSpaceProxy -up-|> Serial_  : <<use>>

}

' ---

@enduml
